include: package:pedantic_mono/analysis_options.yaml

linter:
  rules:

analyzer:
  # https://riverpod.dev/docs/introduction/getting_started#enabling-riverpod_lintcustom_lint
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gform.dart"
    - "**/firebase_options*.dart"
    - ".github/**"
    - "*/functions/*.js"
    - "tool/**"
    - "tools/**"
  errors:
    invalid_annotation_target: ignore
    todo: ignore
    hack: ignore
