name: template
sdkPath: .fvm/flutter_sdk

packages:
  - apps/*
  - packages/cores/*
  - packages/features/*

command:
  bootstrap:
    environment:
      sdk: ^3.6.0
      flutter: ^3.27.0
    dependencies:
      collection: any
      flutter_hooks: any
      freezed_annotation: any
      go_router: any
      hooks_riverpod: ^2.6.1
      intl: any
      json_annotation: any
      logger: any
      riverpod_annotation: ^2.6.1
      slang: ^4.1.0
      slang_flutter: ^4.1.0
    dev_dependencies:
      alchemist: ^0.10.0
      build_runner: any
      custom_lint: any
      flutter_gen_runner: any
      freezed: any
      json_serializable: any
      nilts: any
      pedantic_mono: any
      riverpod_generator: ^2.6.1
      riverpod_lint: ^2.6.1
      slang_build_runner: ^4.1.0
      test: any
    # hooks:
    #   post: grind generate-package-labels && grind generate-package-labeler
  clean:
    hooks:
      post: melos exec --flutter --concurrency=3 -- "flutter clean"
        melos exec --flutter --file-exists="ios/Podfile.lock" -- "cd ios && rm Podfile.lock"
        melos exec --flutter --file-exists="macos/Podfile.lock" -- "cd macos && rm Podfile.lock"

scripts:
  report_test:
    exec: flutter test --no-pub --machine > test_report.log
    packageFilters:
      flutter: true
      dependsOn: test

  # ローカルでフォーマットとdart fix --applyを実行する
  format_and_fix:
    exec: bash "$MELOS_ROOT_PATH/scripts/format.sh"

  report_custom_lint:ci:
    exec: bash "$MELOS_ROOT_PATH/scripts/report-custom-lint-ci.sh"
    packageFilters:
      dependsOn: custom_lint

  regenerate_code: melos run regenerate_by_using_build_runner && melos run regenerate_by_using_gen_slang

  regenerate_by_using_build_runner:
    run: dart run build_runner build -d
    exec:
      orderDependents: true
    packageFilters:
      dependsOn: build_runner

  regenerate_by_using_gen_slang:
    run: dart run slang
    exec:
      orderDependents: true
    packageFilters:
      dependsOn: slang

  watch_build_runner:
    run: dart run build_runner watch -d
    exec:
      orderDependents: true
    packageFilters:
      dependsOn: build_runner

  test_golden:
    run: flutter test --tags=golden
    exec:
      orderDependents: true
    packageFilters:
      dependsOn: alchemist

  test_update_golden:
    run: flutter test --update-goldens
    exec:
      orderDependents: true
    packageFilters:
      dependsOn: alchemist

ide:
  intellij:
    # Disabling IntelliJ's automatic configuration.
    # This is to support different build configurations for environments.
    enabled: false
