name: template
sdkPath: .fvm/flutter_sdk

packages:
  - apps/*
  - packages/cores/*
  - packages/features/*

command:
  bootstrap:
    environment:
      sdk: ^3.5.0
      flutter: ^3.24.0
    dependencies:
      collection:
      flutter_hooks: 
      freezed_annotation:
      go_router: 
      hooks_riverpod: 
      intl: 
      json_annotation: 
      logger:
      riverpod_annotation: 
    dev_dependencies:
      build_runner: 
      custom_lint: 
      freezed: 
      json_serializable: 
      pedantic_mono:
      riverpod_generator: 
      riverpod_lint: 
      test: 
      flutter_gen_runner: 
    hooks:
      post: grind generate-package-labels && grind generate-package-labeler

scripts:
  report_test:
    exec: flutter test --no-pub --machine > test_report.log
    packageFilters:
      flutter: true
      dependsOn: test

  # ローカルでフォーマットとdart fix --applyを実行する
  format_and_fix:
    exec: bash "$MELOS_ROOT_PATH/scripts/format.sh"

  report_custom_lint:ci:
    exec: bash "$MELOS_ROOT_PATH/scripts/report-custom-lint-ci.sh"
    packageFilters:
      dependsOn: custom_lint

  regenerate_code: melos run regenerate_by_using_build_runner && melos run regenerate_by_using_gen_slang

  regenerate_by_using_build_runner:
    run: dart run build_runner build -d
    exec:
      orderDependents: true
    packageFilters:
      dependsOn: build_runner

  watch_build_runner:
    run: dart run build_runner watch -d
    exec:
      orderDependents: true
    packageFilters:
      dependsOn: build_runner

  regenerate_by_using_gen_slang:
    run: dart run slang
    exec:
      orderDependents: true
    packageFilters:
      dependsOn: slang

ide:
  intellij:
    # Disabling IntelliJ's automatic configuration.
    # This is to support different build configurations for environments.
    enabled: false
