name: cores_firebase
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  cores_core:
    path: ../core
  cloud_firestore:
  collection: 
  firebase_analytics:
  firebase_app_check:
  firebase_auth:
  firebase_core:
  firebase_crashlytics:
  firebase_remote_config:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: 
  test: any

flutter:
