name: cores_firebase
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.5.4
  flutter: ^3.24.4

dependencies:
  cloud_firestore:
  cloud_functions:
  collection: 
  cores_core:
    path: ../core
  firebase_analytics:
  firebase_app_check:
  firebase_auth:
  firebase_core:
  firebase_crashlytics:
  firebase_remote_config:
  firebase_storage:
  flutter:
    sdk: flutter
  freezed_annotation: 
  google_sign_in: 
  hooks_riverpod: ^2.6.1 
  riverpod_annotation: ^2.6.1 

dev_dependencies:
  build_runner: 
  flutter_test:
    sdk: flutter
  nilts: any
  pedantic_mono: 
  riverpod_generator: ^2.6.1 
  riverpod_lint: ^2.6.1 
  test: any
