name: cores_core
description: "This package provides core features of app."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  cores_error:
    path: ../error
  flutter:
    sdk: flutter
  flutter_hooks:
  freezed_annotation:
  hooks_riverpod: 
  intl:
  json_annotation:
  logger:
  nested:
  riverpod_annotation: 
  slang: 
  slang_flutter: 
  version:
  visibility_detector:

dev_dependencies:
  build_runner:
  custom_lint:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:
  pedantic_mono:
  riverpod_generator: 
  riverpod_lint: 
  slang_build_runner: 
