name: cores_core
description: "This package provides core features of app."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  cores_firebase:
    path: ../firebase
  flutter:
    sdk: flutter
  flutter_hooks:
  freezed_annotation: 
  hooks_riverpod: ^3.0.0-dev.3
  intl: 
  json_annotation: 
  logger:
  riverpod_annotation: ^3.0.0-dev.3
  version: 
  visibility_detector: 

dev_dependencies:
  build_runner: 
  custom_lint: 
  flutter_test:
    sdk: flutter
  freezed: 
  json_serializable: 
  pedantic_mono:
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
  
