name: cores_core
description: "This package provides core features of app."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: ^3.27.0

dependencies:
  cores_error:
    path: ../error
  flutter:
    sdk: flutter
  flutter_hooks:
  freezed_annotation:
  hooks_riverpod: ^2.6.1 
  intl:
  json_annotation:
  logger:
  nested:
  riverpod_annotation: ^2.6.1 
  slang: ^4.1.0 
  slang_flutter: ^4.1.0 
  version:
  visibility_detector:

dev_dependencies:
  build_runner:
  custom_lint:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:
  nilts: any
  pedantic_mono:
  riverpod_generator: ^2.6.1 
  riverpod_lint: ^2.6.1 
  slang_build_runner: ^4.1.0 
