name: features_github_repository
description: "This package provides features for GitHub repository."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  cores_core:
    path: ../../cores/core
  cores_data:
    path: ../../cores/data
  cores_designsystem:
    path: ../../cores/designsystem
  flutter:
    sdk: flutter
  flutter_hooks: any
  freezed_annotation: any
  hooks_riverpod: ^3.0.0-dev.3
  json_annotation: any
  riverpod_annotation: ^3.0.0-dev.3

dev_dependencies:
  build_runner: any
  custom_lint: any
  freezed: any
  json_serializable: any
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
