name: cores_init
description: "This package provides ways to initialize app."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  cores_core:
    path: ../core
  cores_data:
    path: ../data
  flutter:
    sdk: flutter
  hooks_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3

dev_dependencies:
  custom_lint: 
  pedantic_mono:
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
