name: features_goods
description: "This package provides goods features."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.5.4
  flutter: ^3.24.4

dependencies:
  animations: null
  clock: null
  collection: null
  cores_core:
    path: ../../cores/core
  cores_data:
    path: ../../cores/data
  cores_designsystem:
    path: ../../cores/designsystem
  cores_error:
    path: ../../cores/error
  flutter:
    sdk: flutter
  flutter_hooks: any
  flutter_localizations:
    sdk: flutter
  freezed_annotation: any
  gap: null
  hooks_riverpod: ^2.6.1
  intl: null
  json_annotation: any
  nested: null
  riverpod_annotation: ^2.6.1
  riverpod_paging_utils: null
  slang: null
  slang_flutter: null

dev_dependencies:
  alchemist: ^0.10.0
  build_runner: any
  custom_lint: any
  flutter_test:
    sdk: flutter
  freezed: any
  json_serializable: any
  nilts: any
  pedantic_mono: null
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
  slang_build_runner: null

flutter:
  uses-material-design: true
  assets:
    - assets/image/

# パッケージ内でのみ利用するAssetsは下記の指定が必要
flutter_gen:
  output: lib/src/gen/assets
  assets:
    outputs:
      package_parameter_enabled: true
