name: cores_error
description: "A new Flutter package project."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  collection:
  cores_core:
    path: ../core
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_svg:
  freezed_annotation: 
  gap: 
  hooks_riverpod: ^3.0.0-dev.3
  nested: 
  riverpod_annotation: ^3.0.0-dev.3
  slang: 
  slang_flutter: 

dev_dependencies:
  build_runner: 
  custom_lint: 
  flutter_gen_runner: 
  flutter_test:
    sdk: flutter
  pedantic_mono:
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
  slang_build_runner: 
  theme_extensions_builder: 

flutter:
