name: cores_error
description: "A new Flutter package project."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.5.4
  flutter: ^3.24.4

dependencies:
  collection:
  cores_core:
    path: ../core
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_svg:
  freezed_annotation: 
  gap: 
  hooks_riverpod: ^2.6.1 
  nested: 
  riverpod_annotation: ^2.6.1 
  slang: ^4.1.0 
  slang_flutter: ^4.1.0 

dev_dependencies:
  build_runner: 
  custom_lint: 
  flutter_gen_runner: 
  flutter_test:
    sdk: flutter
  nilts: any
  pedantic_mono:
  riverpod_generator: ^2.6.1 
  riverpod_lint: ^2.6.1 
  slang_build_runner: ^4.1.0 
  theme_extensions_builder: 
