name: cores_shared_preferences
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.5.4
  flutter: ^3.24.4

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.6.1 
  riverpod_annotation: ^2.6.1 
  shared_preferences: 

dev_dependencies:
  build_runner: 
  custom_lint: 
  flutter_test:
    sdk: flutter
  nilts: any
  pedantic_mono:
  riverpod_generator: ^2.6.1 
  riverpod_lint: ^2.6.1 
  test: any
