name: cores_shared_preferences
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: 
  riverpod_annotation: 
  shared_preferences: 

dev_dependencies:
  build_runner: 
  custom_lint: 
  flutter_test:
    sdk: flutter
  pedantic_mono:
  riverpod_generator: 
  riverpod_lint: 
  test: any

flutter:
