name: cores_shared_preferences
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3
  shared_preferences: 

dev_dependencies:
  build_runner: 
  custom_lint: 
  flutter_test:
    sdk: flutter
  pedantic_mono:
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
  test: any

flutter:
