name: features_sample_list
description: "This package provides sample_list features."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  collection:
  cores_core:
    path: ../../cores/core
  cores_data:
    path: ../../cores/data
  cores_designsystem:
    path: ../../cores/designsystem
  flutter:
    sdk: flutter
  flutter_hooks: any 
  flutter_localizations:
    sdk: flutter
  freezed_annotation: any 
  hooks_riverpod: ^3.0.0-dev.3
  intl: 
  json_annotation: any
  nested: 
  riverpod_annotation: ^3.0.0-dev.3
  slang: 
  slang_flutter: 

dev_dependencies:
  build_runner: any 
  custom_lint: any 
  flutter_test:
    sdk: flutter
  freezed: any
  json_serializable: any 
  pedantic_mono: 
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
  slang_build_runner: 

flutter:

# パッケージ内でのみ利用するAssetsは下記の指定が必要
# flutter_gen:
#   output: lib/src/gen/assets
#   assets:
#     outputs:
#       package_parameter_enabled: true
