name: features_sample_list
description: "This package provides sample_list features."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  clock: 
  collection:
  cores_core:
    path: ../../cores/core
  cores_data:
    path: ../../cores/data
  cores_designsystem:
    path: ../../cores/designsystem
  cores_error:
    path: ../../cores/error
  flutter:
    sdk: flutter
  flutter_hooks: any 
  flutter_localizations:
    sdk: flutter
  freezed_annotation: any 
  gap: 
  hooks_riverpod: 
  intl: 
  json_annotation: any
  nested: 
  riverpod_annotation: 
  riverpod_paging_utils:
  slang: 
  slang_flutter: 

dev_dependencies:
  build_runner: any 
  custom_lint: any 
  flutter_test:
    sdk: flutter
  freezed: any
  json_serializable: any 
  pedantic_mono: 
  riverpod_generator: 
  riverpod_lint: 
  slang_build_runner: 

flutter:

# パッケージ内でのみ利用するAssetsは下記の指定が必要
# flutter_gen:
#   output: lib/src/gen/assets
#   assets:
#     outputs:
#       package_parameter_enabled: true
