name: features_user
description: "This package provides user features."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.5.4
  flutter: ^3.24.4

dependencies:
  cloud_firestore:
  collection:
  cores_core:
    path: ../../cores/core
  cores_data:
    path: ../../cores/data
  cores_designsystem:
    path: ../../cores/designsystem
  cores_error:
    path: ../../cores/error
  cores_firebase:
    path: ../../cores/firebase
  features_setting:
    path: ../../features/setting
  firebase_auth:
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_localizations:
    sdk: flutter
  freezed_annotation:
  gap:
  hooks_riverpod: ^2.6.1
  intl:
  material_design_icons_flutter:
  nested:
  riverpod_annotation: ^2.6.1
  slang:
  slang_flutter:

dev_dependencies:
  build_runner:
  custom_lint:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  freezed: any
  json_serializable:
  nilts: any
  pedantic_mono:
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
  slang_build_runner:

flutter:
  # Assets & Fonts
  assets:
    - assets/images/

flutter_gen:
  output: lib/src/gen/assets
  assets:
    outputs:
      package_parameter_enabled: true
