name: features_user
description: "This package provides user features."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  cloud_firestore:
  collection:
  cores_core:
    path: ../../cores/core
  cores_data:
    path: ../../cores/data
  cores_designsystem:
    path: ../../cores/designsystem
  cores_error:
    path: ../../cores/error
  cores_firebase:
    path: ../../cores/firebase
  features_setting:
    path: ../../features/setting
  firebase_auth: 
  flutter:
    sdk: flutter
  flutter_hooks: 
  flutter_localizations:
    sdk: flutter
  freezed_annotation: 
  gap: 
  hooks_riverpod: 
  intl: 
  material_design_icons_flutter:
  nested: 
  riverpod_annotation: 
  riverpod_paging_utils:
  slang: 
  slang_flutter: 

dev_dependencies:
  build_runner: 
  custom_lint: 
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  freezed: any
  json_serializable: 
  pedantic_mono: 
  riverpod_generator: 
  riverpod_lint: 
  slang_build_runner: 

flutter:
  # Assets & Fonts
  assets:
    - assets/images/

flutter_gen:
  output: lib/src/gen/assets
  assets:
    outputs:
      package_parameter_enabled: true
