name: features_user
description: "This package provides user features."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  cloud_firestore:
  collection:
  cores_core:
    path: ../../cores/core
  cores_data:
    path: ../../cores/data
  cores_designsystem:
    path: ../../cores/designsystem
  cores_firebase:
    path: ../../cores/firebase
  firebase_auth: 
  flutter:
    sdk: flutter
  flutter_hooks: 
  flutter_localizations:
    sdk: flutter
  freezed_annotation: 
  hooks_riverpod: ^3.0.0-dev.3
  intl: 
  nested: 
  riverpod_annotation: ^3.0.0-dev.3
  slang: 
  slang_flutter: 

dev_dependencies:
  build_runner: 
  custom_lint: 
  flutter_test:
    sdk: flutter
  freezed: any
  json_serializable: 
  pedantic_mono: 
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
  slang_build_runner: 

flutter:
