name: features_app_update
description: "This package provides app_update features."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.5.4
  flutter: ^3.24.4

dependencies:
  adaptive_dialog: null
  collection: null
  cores_core:
    path: ../../cores/core
  cores_data:
    path: ../../cores/data
  cores_designsystem:
    path: ../../cores/designsystem
  cores_firebase:
    path: ../../cores/firebase
  flutter:
    sdk: flutter
  flutter_hooks: null
  flutter_localizations:
    sdk: flutter
  freezed_annotation: null
  hooks_riverpod: ^2.6.1
  intl: null
  nested: null
  riverpod_annotation: ^2.6.1
  slang: null
  slang_flutter: null
  store_redirect:
  version: null

dev_dependencies:
  build_runner: null
  custom_lint: null
  flutter_test:
    sdk: flutter
  freezed: any
  json_serializable: null
  nilts: any
  pedantic_mono: null
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
  slang_build_runner: null
