name: catalog
description: "A UI catalog application."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: ^3.27.0

dependencies:
  cores_designsystem:
    path: ../../packages/cores/designsystem
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  widgetbook: any
  widgetbook_annotation: any

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  pedantic_mono: any
  widgetbook_generator: any

flutter:
  uses-material-design: true
