name: catalog
description: "A UI catalog application."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  cores_designsystem:
    path: ../../packages/cores/designsystem
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  widgetbook: ^3.7.1
  widgetbook_annotation: ^3.1.0

dev_dependencies:
  build_runner: any
  custom_lint: any
  pedantic_mono: any
  widgetbook_generator: ^3.7.0

flutter:
  uses-material-design: true
