name: features_setting
description: "This package provides setting feature."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  cores_core:
    path: ../../cores/core
  cores_data:
    path: ../../cores/data
  cores_designsystem:
    path: ../../cores/designsystem
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_localizations:
    sdk: flutter
  hooks_riverpod: ^3.0.0-dev.3
  intl: 
  material_design_icons_flutter:
  riverpod_annotation: ^3.0.0-dev.3
  settings_ui:
  slang: 

dev_dependencies:
  build_runner: 
  flutter_gen_runner: 
  pedantic_mono:
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_gen:
  output: lib/src/gen/assets
  assets:
    outputs:
      package_parameter_enabled: true
