name: features_setting
description: "This package provides setting feature."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.5.4
  flutter: ^3.24.4

dependencies:
  adaptive_dialog: 
  cores_core:
    path: ../../cores/core
  cores_data:
    path: ../../cores/data
  cores_designsystem:
    path: ../../cores/designsystem
  cores_error:
    path: ../../cores/error
  features_user:
    path: ../../features/user
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_localizations:
    sdk: flutter
  flutter_settings_ui: any
  hooks_riverpod: ^2.6.1 
  intl: 
  material_design_icons_flutter:
  nested: 
  riverpod_annotation: ^2.6.1
  slang: ^4.1.0 
  slang_flutter: ^4.1.0 

dev_dependencies:
  build_runner: 
  flutter_gen_runner: 
  nilts: any
  pedantic_mono:
  riverpod_generator: ^2.6.1 
  riverpod_lint: ^2.6.1 
  slang_build_runner: ^4.1.0 

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_gen:
  output: lib/src/gen/assets
  assets:
    outputs:
      package_parameter_enabled: true
