name: features_setting
description: "This package provides setting feature."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  adaptive_dialog: 
  cores_core:
    path: ../../cores/core
  cores_data:
    path: ../../cores/data
  cores_designsystem:
    path: ../../cores/designsystem
  cores_error:
    path: ../../cores/error
  features_user:
    path: ../../features/user
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_localizations:
    sdk: flutter
  hooks_riverpod: 
  intl: 
  material_design_icons_flutter:
  nested: 
  riverpod_annotation: 
  settings_ui:
  slang: 
  slang_flutter: 

dev_dependencies:
  build_runner: 
  flutter_gen_runner: 
  pedantic_mono:
  riverpod_generator: 
  riverpod_lint: 
  slang_build_runner: 

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_gen:
  output: lib/src/gen/assets
  assets:
    outputs:
      package_parameter_enabled: true
