name: cores_designsystem
description: "This package provides style definitions, themes, etc."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  animations: null
  collection: null
  cores_core:
    path: ../core
  cores_shared_preferences:
    path: ../shared_preferences
  dynamic_color: null
  flutter:
    sdk: flutter
  flutter_hooks: null
  flutter_svg: null
  freezed_annotation: null
  gap: null
  gauge_indicator: null
  hooks_riverpod: ^2.6.1
  linked_scroll_controller: null
  material_color_utilities: null
  nested: null
  responsive_framework: ^1.5.1
  riverpod_annotation: ^2.6.1
  shimmer: null
  slang: null
  slang_flutter: null
  sliver_tools: null
  theme_tailor_annotation: null
  url_launcher: null

dev_dependencies:
  build_runner: null
  custom_lint: null
  flutter_gen_runner: null
  flutter_test:
    sdk: flutter
  freezed: null
  nilts: any
  pedantic_mono: null
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
  slang_build_runner: null
  theme_tailor: null

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/src/gen/assets
  integrations:
    flutter_svg: true
  assets:
    outputs:
      package_parameter_enabled: true
