name: cores_designsystem
description: "This package provides style definitions, themes, etc."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  animations:
  collection:
  cores_core:
    path: ../core
  cores_shared_preferences:
    path: ../shared_preferences
  dynamic_color:
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_svg:
  freezed_annotation: 
  gap: 
  gauge_indicator: 
  hooks_riverpod: ^3.0.0-dev.3
  material_color_utilities:
  nested: 
  riverpod_annotation: ^3.0.0-dev.3
  shimmer:
  slang: 
  slang_flutter: 
  theme_extensions_builder_annotation: 
  url_launcher:

dev_dependencies:
  build_runner: 
  flutter_gen_runner: 
  flutter_test:
    sdk: flutter
  pedantic_mono:
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
  slang_build_runner: 
  theme_extensions_builder: 

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_gen:
  output: lib/src/gen/assets
  assets:
    outputs:
      package_parameter_enabled: true
