name: cores_designsystem
description: "This package provides style definitions, themes, etc."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.7.0
  flutter: ^3.29.0

dependencies:
  adaptive_dialog: ^2.4.0
  animations: null
  collection: null
  cores_domain:
    path: ../domain
  dynamic_color: null
  flutter:
    sdk: flutter
  flutter_hooks: null
  flutter_svg: null
  freezed_annotation: null
  gap: null
  gauge_indicator: null
  hooks_riverpod: ^2.6.1
  linked_scroll_controller: null
  material_color_utilities: null
  nested: null
  responsive_framework: ^1.5.1
  riverpod_annotation: ^2.6.1
  shimmer: null
  slang: ^4.1.0
  slang_flutter: ^4.1.0
  sliver_tools: null
  store_redirect: ^2.0.3
  theme_tailor_annotation: null
  url_launcher: null

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  flutter_gen_runner: null
  flutter_test:
    sdk: flutter
  freezed: null
  nilts: any
  pedantic_mono: null
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
  slang_build_runner: ^4.1.0
  theme_tailor: null

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/src/gen/assets
  integrations:
    flutter_svg: true
  assets:
    outputs:
      package_parameter_enabled: true

resolution: workspace
