name: cores_designsystem
description: "This package provides style definitions, themes, etc."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  flutter:
    sdk: flutter
  theme_extensions_builder_annotation: 

dev_dependencies:
  build_runner: 
  flutter_gen_runner: 
  flutter_test:
    sdk: flutter
  pedantic_mono:
  theme_extensions_builder: 

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_gen:
  output: lib/src/gen/assets
  assets:
    outputs:
      package_parameter_enabled: true
