name: cores_designsystem
description: "This package provides style definitions, themes, etc."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  animations: 
  collection:
  cores_core:
    path: ../core
  cores_shared_preferences:
    path: ../shared_preferences
  dynamic_color:
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_svg:
  freezed_annotation: 
  gap: 
  gauge_indicator: 
  hooks_riverpod: ^2.6.1 
  linked_scroll_controller: 
  material_color_utilities:
  nested: 
  riverpod_annotation: ^2.6.1 
  shimmer:
  slang: 
  slang_flutter: 
  sliver_tools:
  theme_tailor_annotation:  
  url_launcher:

dev_dependencies:
  build_runner: 
  custom_lint: 
  flutter_gen_runner: 
  flutter_test:
    sdk: flutter
  freezed:
  nilts: any
  pedantic_mono:
  riverpod_generator: ^2.6.1 
  riverpod_lint: ^2.6.1 
  slang_build_runner: 
  theme_tailor: 

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/src/gen/assets
  integrations:
    flutter_svg: true
  assets:
    outputs:
      package_parameter_enabled: true
