name: features_{{feature_name.snakeCase()}}
description: "This package provides {{feature_name.snakeCase()}} features."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  collection:
  cores_auth:
    path: ../../cores/auth    
  cores_core:
    path: ../../cores/core
  cores_data:
    path: ../../cores/data
  cores_designsystem:
    path: ../../cores/designsystem
  flutter:
    sdk: flutter
  flutter_hooks: 
  flutter_localizations:
    sdk: flutter
  freezed_annotation: 
  hooks_riverpod: ^3.0.0-dev.3
  intl: 
  riverpod_annotation: ^3.0.0-dev.3
  slang: 
  slang_flutter: 

dev_dependencies:
  build_runner: 
  custom_lint: 
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: 
  pedantic_mono: 
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
  slang_build_runner: 

flutter:
