name: features_debug_mode
description: "This package provides features for Debug Mode"
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  cores_core:
    path: ../../cores/core
  cores_data:
    path: ../../cores/data
  cores_designsystem:
    path: ../../cores/designsystem
  cores_error:
    path: ../../cores/error
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_hooks: any
  go_router: ^13.2.1
  hooks_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3

dev_dependencies:
  build_runner: any
  custom_lint: any
  pedantic_mono: any
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
