name: cores_{{package_name.snakeCase()}}
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  collection:
  cores_core:
    path: ../core 
  flutter:
    sdk: flutter
  nested: 

dev_dependencies:
  custom_lint: 
  flutter_test:
    sdk: flutter
  pedantic_mono: 
  test: ^1.24.0
