name: features_maintenance
description: "This package provides maintenance features."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  collection:
  cores_core:
    path: ../../cores/core
  cores_data:
    path: ../../cores/data
  cores_designsystem:
    path: ../../cores/designsystem
  cores_firebase:
    path: ../../cores/firebase
  flutter:
    sdk: flutter
  flutter_hooks: 
  flutter_localizations:
    sdk: flutter
  freezed_annotation: 
  hooks_riverpod: 
  intl: 
  nested: 
  riverpod_annotation: 
  slang: 
  slang_flutter: 

dev_dependencies:
  build_runner: 
  custom_lint: 
  flutter_test:
    sdk: flutter
  freezed: any
  json_serializable: 
  nilts: any
  pedantic_mono: 
  riverpod_generator: 
  riverpod_lint: 
  slang_build_runner: 
