name: Check Markdown

on:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      # https://github.com/DavidAnson/markdownlint-cli2-action
      - name: Check Markdown
        uses: DavidAnson/markdownlint-cli2-action@b4c9feab76d8025d1e83c653fa3990936df0e6c8 # v16.0.0
